[[factions]]
name = "test1"
alliances = []
auras = []
wealth = 0
provision_rate = 10.0
reserve = 0
score = 0
pp = 40
pp_gain = 10
withdraw_rate = 0.2
min_withdraw_rate = 0.2
attack_modifier = 1.0
defense_modifier = 1.5

[[factions]]
name = "test2"
alliances = []
auras = []
wealth = 0
provision_rate = 10.0
reserve = 0
score = 0
pp = 40
pp_gain = 10
withdraw_rate = 0.2
min_withdraw_rate = 0.2
attack_modifier = 1.0
defense_modifier = 1.5

[[armies]]
name = "army1"
owner = "test1"
location = "s1"
size = 2000

[[armies]]
name = "army2"
owner = "test2"
location = "s2"
size = 2000

[[states]]
name = "s1"
owner = "test1"
population = 30000
tax_rate = 0.1
max_tax_rate = 0.2
attack_modifier = 1.0
defense_modifier = 1.0

[[states]]
name = "s2"
owner = "test2"
population = 30000
tax_rate = 0.1
max_tax_rate = 0.2
attack_modifier = 1.0
defense_modifier = 1.0
